ADD_KIT ~RAHUGM~
    ~RAHUGM 1 1 1 1 1 1 1 1~
    ~RAHUGM 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAHUGM 3 12 3 13 3 17~
	~RAHUGM 0 0 0 0 0 0~
	~RAHUGM 3 12 3 13 3 17~
    ~RAHUGM 3 12 3 13 3 17~
	~RAHUGM 0 0 0 1 1 0 1 1 0~
	~RAHUGM 0 0 0 0 0 0~
	~IHateUndead\Tables\RAHUGM.2da~
	~K_B_H	K_B_D   K_B_G   K_B_E   K_B_HE   K_B_HL   K_B_HO~
	~0x00000000 5~
	~RAHUGM~
	~* * * * RING05 RING34 CLCK26 BOOT04 AMUL25 BRAC17 * * * * * * * SW1H31 BOW15 *~
	SAY @701
	SAY @702
	SAY @703

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAHUGM~
		clascolr = ~63 62 66 43 64~
END

COPY_EXISTING ~LUBa0.2da~ ~override\LURAHUGM.2da~
SET_2DA_ENTRY 6  1 9 ~*         ~
SET_2DA_ENTRY 6  4 9 ~*         ~
SET_2DA_ENTRY 6  5 9 ~*         ~
SET_2DA_ENTRY 6  6 9 ~*         ~
SET_2DA_ENTRY 10 1 9 ~*         ~
SET_2DA_ENTRY 10 4 9 ~*         ~
SET_2DA_ENTRY 10 5 9 ~*         ~
SET_2DA_ENTRY 10 6 9 ~*         ~
PRETTY_PRINT_2DA

CREATE spl ~RAGMF~

COPY_EXISTING ~RAGMF.spl~ override
LPF ADD_ABILITIES    INT_VAR abil = 1 END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 251 target = 2 timing = 9 STR_VAR insert_point = 0 resource = ~RAGMF1~ END

COPY ~IHateUndead\Spl\RAGMF1.spl~  override	SAY NAME1 @714
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@715) END

COPY ~IHateUndead\Spl\RAGM1.bam~ override

COPY ~IHateUndead\Spl\RAGM1.spl~ override	SAY NAME1 @704	SAY UNIDENTIFIED_DESC @705
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = EVAL ~%RA_Deaf%~ END
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 267 parameter1 = EVAL ~%RA_Deaf%~ END
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 337 parameter1 = EVAL ~%RA_Deaf%~ END

COPY ~IHateUndead\Spl\RAGM2.bam~ override

COPY ~IHateUndead\Spl\RAGM2.spl~ override	SAY NAME1 @706	SAY UNIDENTIFIED_DESC @707
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = EVAL ~%RA_Berserk%~ END
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 267 parameter1 = EVAL ~%RA_Berserk%~ END
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 337 parameter1 = EVAL ~%RA_Berserk%~ END

COPY ~IHateUndead\Spl\RAGM3.bam~ override

COPY ~IHateUndead\Spl\RAGM3.spl~ override	SAY NAME1 @708	SAY UNIDENTIFIED_DESC @709
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = EVAL ~%RA_Panic%~ END
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 267 parameter1 = EVAL ~%RA_Panic%~ END
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 337 parameter1 = EVAL ~%RA_Panic%~ END

COPY ~IHateUndead\Spl\RAGM4.bam~ override

COPY ~IHateUndead\Spl\RAGM4.spl~ override	SAY NAME1 @710	SAY UNIDENTIFIED_DESC @711
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = EVAL ~%RA_Dominated%~ END
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 267 parameter1 = EVAL ~%RA_Dominated%~ END
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 337 parameter1 = EVAL ~%RA_Dominated%~ END

COPY ~IHateUndead\Spl\RAGM5.bam~ override

COPY ~IHateUndead\Spl\RAGM5.spl~ override	SAY NAME1 @712	SAY UNIDENTIFIED_DESC @713
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = EVAL ~%RA_Stunned%~ END
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 267 parameter1 = EVAL ~%RA_Stunned%~ END
LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 337 parameter1 = EVAL ~%RA_Stunned%~ END

//Restrictions
	
COPY_EXISTING_REGEXP GLOB ~^.+\.itm$~ ~override~
PATCH_IF (SOURCE_SIZE > 0x71) BEGIN
		READ_BYTE 0x18 flags1
		PATCH_IF ((flags1 & BIT3) = BIT3) BEGIN
			READ_ASCII	0x22 animation (2)
			TO_UPPER animation
			PATCH_MATCH	~%animation%~ WITH
				~3A~ ~2A~ ~D1~ ~D2~ ~D3~ ~D4~ ~C0~ ~C1~ ~C2~ ~C3~ ~C4~ ~C5~ ~C6~ BEGIN
					LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RAHUGM~) parameter2 = 9 END
				END
				DEFAULT
			END
		END
	END
BUT_ONLY	

//EoF