ADD_KIT ~RAUM~
    ~RAUM 1 1 1 1 1 1 1 1~
    ~RAUM 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAUM 3 12 3 13 3 17~
	~RAUM 0 0 0 0 0 0~
	~RAUM 99 99 99 99 99 99~
    ~RAUM 18 18 18 18 18 18~
	~RAUM 0 1 0 1 1 0 0 1 0~
	~RAUM 0 0 0 0 0 0~
	~IHateUndead\Tables\RAUM.2da~
	~K_B_H	K_B_D   K_B_G   K_B_E   K_B_HE   K_B_HL   K_B_HO~
	~0x00000400 5~
	~RAUM~
	~CHAIN13 * * * RING05 RING34 CLCK26 BOOT04 AMUL25 BRAC17 * * * * * * * SW1H31 BOW15 *~
	SAY @701
	SAY @702
	SAY @703

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAUM~
		clascolr = ~6 220 169 242 236~
END

COPY "IHateUndead\Spl\RAUMSO1.spl" override	SAY NAME1 @704	SAY UNIDENTIFIED_DESC @705

COPY "IHateUndead\Spl\RAUMSO2.spl" override	SAY NAME1 @706	SAY UNIDENTIFIED_DESC @707

COPY "IHateUndead\Spl\RAUMSO3.spl" override	SAY NAME1 @708	SAY UNIDENTIFIED_DESC @709

COPY "IHateUndead\Spl\RAUMSO4.spl" override	SAY NAME1 @710	SAY UNIDENTIFIED_DESC @711

COPY "IHateUndead\Spl\RAUMSO5.spl" override	SAY NAME1 @712	SAY UNIDENTIFIED_DESC @713

COPY ~IHateUndead\Eff\Mourner\Copy~ ~override~

COPY ~IHateUndead\Eff\Mourner\RASO2EF3.eff~ ~override~
	WRITE_LONG 0x1c %RA_Berserk%

COPY ~IHateUndead\Eff\Mourner\RASO3EF3.eff~ ~override~
    WRITE_LONG 0x1c %RA_Held%

COPY ~IHateUndead\Eff\Mourner\RASO4EF3.eff~ ~override~
	WRITE_LONG 0x1c %RA_Dominated%

COPY ~IHateUndead\Eff\Mourner\RASO5EF3.eff~ ~override~
	WRITE_LONG 0x1c %RA_Feebleminded%
	
COPY "IHateUndead\Tables\LURAUM.2DA" override

COPY "IHateUndead\Spl\RAUMFE.spl" override

COPY "IHateUndead\Spl\RAUMRE.spl" override	SAY NAME1 @714
    LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@715) END
	
ACTION_FOR_EACH file IN ~RAUMBO~ ~RAUMDD~ ~RAUMGW~ ~RAUMLC~ ~RAUMMF~ BEGIN
  COPY ~IHateUndead\Bam\GraveMourner\%file%.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~IHateUndead\Bam\GraveMourner\MOS%original_base_index%.pvrz~
    END
  END
END

//EoF