ADD_KIT ~RAHUPM~
    ~RAHUPM 1 1 1 1 1 0 0 0~
    ~RAHUPM 0 1 0 0 1 0 0 1 0 1 1 0 0 1 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAHUPM 3 9 11 3 9 3~
	~RAHUPM 0 0 0 0 0 0~
	~RAHUPM 3 9 11 3 9 3~
    ~RAHUPM 3 9 11 3 9 3~
	~RAHUPM 0 1 0 0 0 0 0 0 0~
	~RAHUPM 0 0 0 0 0 0~
	~IHateUndead\Tables\RAHUPM.2da~
	~K_MN_H~
	~0x00000000 20~
	~MO0~
	~* * * * RING29 RING39 CLCK05 BOOT04 AMUL27 BRAC16 BELT10 * * * * * * * * *~
	SAY @901
	SAY @902
	SAY @903

LAF fl#add_kit_ee 
	STR_VAR
		kit_name = ~RAHUPM~	
		clascolr = ~6 110 186 185 187~
		clasiskl = ~0 0 0 0 0 5 0~
		thiefscl = ~0 0 0 100 100 100 0 0~
END

CREATE spl ~RAPMF~

COPY_EXISTING ~RAPMF.spl~ override
LPF ADD_ABILITIES	 INT_VAR abil = 1 END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 321 target = 2 timing = 9                                               STR_VAR insert_point = 0 resource = ~RAPMF~ END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 178 target = 2 timing = 9 parameter1 = 4    parameter2 = 3  special = 2 STR_VAR insert_point = 1 END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 179 target = 2 timing = 9 parameter1 = 4    parameter2 = 3  special = 2 STR_VAR insert_point = 2 END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 178 target = 2 timing = 9 parameter1 = 202  parameter2 = 5  special = 2 STR_VAR insert_point = 3 END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 179 target = 2 timing = 9 parameter1 = 202  parameter2 = 5  special = 2 STR_VAR insert_point = 4 END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 178 target = 2 timing = 9 parameter1 = 204  parameter2 = 5  special = 2 STR_VAR insert_point = 5 END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 179 target = 2 timing = 9 parameter1 = 204  parameter2 = 5  special = 2 STR_VAR insert_point = 6 END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 101 target = 2 timing = 9                   parameter2 = 32             STR_VAR insert_point = 7 END
LPF ADD_SPELL_EFFECT INT_VAR opcode = 206 target = 2 timing = 9 parameter1 = ~-1~                             STR_VAR insert_point = 8 resource = ~RAPMF~ END

//Hold Undead

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_HOLD_UNDEAD[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_HOLD_UNDEAD~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAPM1.spl~
LPM ~SPELL_TO_INNATE~

END

//Repulse Undead

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_REPULSE_UNDEAD[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_REPULSE_UNDEAD~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAPM2.spl~
LPM ~SPELL_TO_INNATE~

END

//Control Undead

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]WIZARD_CONTROL_UNDEAD[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~WIZARD_CONTROL_UNDEAD~	RET	spell_res	END

COPY_EXISTING	~%spell_res%.spl~	~override/RAPM3.spl~
LPM ~SPELL_TO_INNATE~

END

COPY ~IHateUndead\Spl\RAPM4.spl~  override
SAY NAME1 @904 SAY NAME2 @904 SAY UNIDENTIFIED_DESC @905 SAY DESC @905

COPY ~IHateUndead\Spl\RAPM4.bam~  override

COPY ~IHateUndead\Spl\RAPM41.spl~ override

COPY ~IHateUndead\Spl\RAPM41.eff~ override

//EoF