ADD_KIT ~RAHUSR~
    ~RAHUSR 0 0 1 1 0 1 0 0~
    ~RAHUSR 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 1 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAHUSR 3 3 3 3 9 12~
	~RAHUSR 0 0 0 0 0 0~
	~RAHUSR 99 99 99 99 99 99~
    ~RAHUSR 0 0 0 0 15 0~
	~RAHUSR 1 1 0 0 0 0 0 0 0~
	~RAHUSR 1 0 1 1 0 1~
	~IHateUndead\Tables\RAHUSR.2da~
	~K_C_H	K_C_D   K_C_G   K_C_E   K_C_HE   K_C_HL   K_C_HO~
	~0x00000000 3~
	~RAHUSR~
	~PLAT12 SHLD25 HELM16 * RING22 RING31 CLCK05 BOOT04 AMUL27 BRAC10 * * * * * * * BLUN25 HAMM09 STAF10~
	SAY @201
	SAY @202
	SAY @203

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAHUSR~		
		clascolr = ~6 15 14 242 28~
		clswpbon = ~0 0 3~
END

ACTION_IF FILE_EXISTS_IN_GAME ~RASPHERE.marker~ BEGIN

	LAF RA_SPHERE_COMPAT STR_VAR kitname = ~RAHUSR~ clabfile = ~RAHUSR~ END

END

COPY "IHateUndead\Tables\LURAHUSR.2DA" override

COPY_EXISTING ~SPPR409.spl~ ~override\RAURFE.spl~
LPM I_HATE_UNDEAD_FEATURES
LPF ADD_SPELL_EFFECT    INT_VAR opcode = 323 target = 2 timing = 9 resist_dispel = 0 parameter1 = 3 parameter2 = 0             END
LPF ADD_SPELL_EFFECT    INT_VAR opcode = 101 target = 2 timing = 9 resist_dispel = 0 parameter1 = 0 parameter2 = 32            END
LPF ADD_SPELL_EFFECT    INT_VAR opcode = 178 target = 2 timing = 9 resist_dispel = 0 parameter1 = 4 parameter2 = 3 special = 3 END
LPF ADD_SPELL_EFFECT    INT_VAR opcode = 179 target = 2 timing = 9 resist_dispel = 0 parameter1 = 4 parameter2 = 3 special = 3 END

COPY "IHateUndead\Spl\RAURRS.spl" override

COPY "IHateUndead\Spl\RAURRE.spl" override	SAY NAME1 @204	SAY UNIDENTIFIED_DESC @205

ACTION_IF GAME_IS ~bgee~ THEN BEGIN
  // Raise Dead
	COPY_EXISTING ~SCRL63.itm~ override
      LPF ADD_ITEM_EQEFFECT
        INT_VAR
          opcode = 319
          target = 1
          parameter1 = (RAHUSR + 0x4000)
          parameter2 = 9
          timing = 2
          special = RESOLVE_STR_REF (@202)
      END
	BUT_ONLY
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN
  // Raise Dead - Rod of Resurrection
  ACTION_FOR_EACH item_unusability IN ~SCRL63~ ~RODS03~ BEGIN
	COPY_EXISTING ~%item_unusability%.itm~ override
      LPF ADD_ITEM_EQEFFECT
        INT_VAR
          opcode = 319
          target = 1
          parameter1 = (RAHUSR + 0x4000)
          parameter2 = 9
          timing = 2
          special = RESOLVE_STR_REF (@202)
      END
	BUT_ONLY
  END
END

ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
  // Raise Dead - Resurrection - Staff of Moradin's Breath +2 - Belt of Bones - Staff of the Hanged Man's Glee +1
  ACTION_FOR_EACH item_unusability IN ~SPPR504C~ ~SPPR712C~ ~MORADIN~ ~BELTBON~ ~XSTAFHMG~ BEGIN
	COPY_EXISTING ~%item_unusability%.itm~ override
      LPF ADD_ITEM_EQEFFECT
        INT_VAR
          opcode = 319
          target = 1
          parameter1 = (RAHUSR + 0x4000)
          parameter2 = 9
          timing = 2
          special = RESOLVE_STR_REF (@202)
      END
	BUT_ONLY
  END
END

COPY ~IHateUndead\Bam\SpiritRedeemer\RAURRE.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~IHateUndead\Bam\SpiritRedeemer\MOS%original_base_index%.pvrz~
    END
  END
  
//EoF