ADD_KIT ~RAUS~
    ~RAUS 1 0 1 1 0 0 0 0~
    ~RAUS 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAUS 3 3 16 9 16 3~
	~RAUS 0 0 0 0 0 0~
	~RAUS 99 99 99 99 99 99~
    ~RAUS 0 0 16 15 16 0~
	~RAUS 1 0 0 1 0 0 1 0 0~
	~RAUS 1 1 0 1 0 0~
	~IHateUndead\Tables\RAUS.2da~
	~K_M_H~
	~0x00001000 1~
	~Ma0~
	~CLCK12 * * * RING09 RING39 CLCK02 BOOT01 AMUL21 BRAC03 * * * * * * * * * STAF11~
	SAY @301
	SAY @302
	SAY @303

LAF fl#add_kit_ee
	STR_VAR
		kit_name = ~RAUS~		
		clascolr = ~6 47 66 242 65~
		hpclass = ~HPRAUS~
END

COPY "IHateUndead\Spl\RAUSFE.spl" override

COPY_EXISTING ~SPPR413.spl~ ~override\RAUSFE1.spl~
LPM I_HATE_UNDEAD_FEATURES

COPY_EXISTING ~SPPR409.spl~ ~override\RAUSFE2.spl~
LPM I_HATE_UNDEAD_FEATURES

COPY "IHateUndead\Spl\RAUSSS.spl" override	SAY NAME1 @304	SAY UNIDENTIFIED_DESC @305
    LPF ALTER_EFFECT INT_VAR match_parameter1 = 1 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@306) END
    LPF ALTER_EFFECT INT_VAR match_parameter1 = 2 match_opcode = 139 parameter1 = RESOLVE_STR_REF (@307) END
	
COPY "IHateUndead\Tables\HPRAUS.2da" override

COPY ~IHateUndead\Bam\UndeadSlayer\RAUSSS.bam~ ~override~
    LPF UPDATE_PVRZ_INDICES
    RET
      original_base_index
      new_base_index
    END

  ACTION_IF (original_base_index >= 0 AND new_base_index >= 0) BEGIN
    LAF INSTALL_PVRZ
    INT_VAR
      original_base_index
      new_base_index
    STR_VAR
      source_file = EVAL ~IHateUndead\Bam\UndeadSlayer\MOS%original_base_index%.pvrz~
    END
  END

//EoF