ACTION_IF GAME_IS ~bgee~ THEN BEGIN
  STRING_SET ~25365~ @401
  STRING_SET ~24289~ @401
END

ACTION_IF GAME_IS ~bg2ee eet~ THEN BEGIN
  STRING_SET ~25208~ @401
END

ACTION_IF GAME_IS ~iwdee~ THEN BEGIN
  STRING_SET ~37141~ @402
  STRING_SET ~25208~ @402
END

COPY_EXISTING ~CLABPA04.2DA~ ~override~
SET_2DA_ENTRY 6 1 40 ~AP_RAUHF~
SET_2DA_ENTRY 6 3 40 ~AP_RAUHF~
SET_2DA_ENTRY 4 5 40 ~GA_RAUH1~
PRETTY_PRINT_2DA
BUT_ONLY

CREATE spl ~RAHRF~

COPY_EXISTING ~RAHRF.spl~ override
LPF ADD_ABILITIES	   INT_VAR abil = 2 END
LPF ALTER_SPELL_HEADER INT_VAR header = 2 min_level = 3  END
LPF ADD_SPELL_EFFECT   INT_VAR header = 2 opcode = 323 target = 2 timing = 9 parameter1 = 2                             STR_VAR insert_point = 1  END
LPF ADD_SPELL_EFFECT   INT_VAR header = 1 opcode = 178 target = 2 timing = 9 parameter1 = 4 parameter2 = 3  special = 3 STR_VAR insert_point = 0  END
LPF ADD_SPELL_EFFECT   INT_VAR header = 1 opcode = 179 target = 2 timing = 9 parameter1 = 4 parameter2 = 3  special = 3 STR_VAR insert_point = 1  END

COPY ~IHateUndead\Spl\RAUH1.spl~ override SAY NAME1 @403	SAY UNIDENTIFIED_DESC @404

COPY ~IHateUndead\Spl\RAUH1.itm~ override SAY NAME1 @403	SAY NAME2 @403

COPY ~IHateUndead\Spl\RAUH1.bam~ override
    
//EoF