ADD_KIT ~RAHUUP~
    ~RAHUUP 1 1 1 1 1 1 1 1~
    ~RAHUUP 0 0 0 0 0 0 0 0 0 2 0 2 0 0 0 0 2 2 2 0 0 2 2 2 0 0 0 0 2 2 2 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0~
	~RAHUUP 13 13 14 3 16 3~
	~RAHUUP 0 0 0 0 0 -2~
	~RAHUUP 13 13 14 3 16 3~
    ~RAHUUP 13 13 14 3 16 3~
	~RAHUUP 0 0 0 1 0 0 0 0 0~
	~RAHUUP 0 0 0 0 0 0~
	~IHateUndead\Tables\RAHUUP.2da~
	~K_R_H	K_R_D   K_R_G   K_R_E   K_R_HE   K_R_HL   K_R_HO~
	~0x00000000 12~
	~Ra0~
	~LEAT19 BLUN25 HELM16 * RING27 RING31 CLCK02 BOOT01 AMUL27 BRAC10 * * * * * * * SW1H31 AX1H10 STAF08~
	SAY @101
	SAY @102
	SAY @103

LAF fl#add_kit_ee
	INT_VAR										
		fallen_notice = RESOLVE_STR_REF (@104)
	STR_VAR
		kit_name = ~RAHUUP~		
		clascolr = ~6 160 164 242 163~
END

COPY "IHateUndead\Spl\RAUPF.spl"  override
LPF ALTER_EFFECT INT_VAR match_parameter1 =  1 match_opcode = 267 parameter1 = EVAL "%RA_Panic%"       END
LPF ALTER_EFFECT INT_VAR match_parameter1 =  2 match_opcode = 267 parameter1 = EVAL "%RA_MoralFail%"   END
LPF ALTER_EFFECT INT_VAR match_parameter1 =  3 match_opcode = 267 parameter1 = EVAL "%RA_Diseased%"    END
LPF ALTER_EFFECT INT_VAR match_parameter1 =  4 match_opcode = 267 parameter1 = EVAL "%RA_FoulDisease%" END
LPF ALTER_EFFECT INT_VAR match_parameter1 =  5 match_opcode = 267 parameter1 = EVAL "%RA_Drain1%"      END
LPF ALTER_EFFECT INT_VAR match_parameter1 =  6 match_opcode = 267 parameter1 = EVAL "%RA_Drain2%" 	   END
LPF ALTER_EFFECT INT_VAR match_parameter1 =  7 match_opcode = 267 parameter1 = EVAL "%RA_Drain3%" 	   END
LPF ALTER_EFFECT INT_VAR match_parameter1 =  8 match_opcode = 267 parameter1 = EVAL "%RA_Drain4%" 	   END
LPF ALTER_EFFECT INT_VAR match_parameter1 =  9 match_opcode = 267 parameter1 = EVAL "%RA_Drain5%" 	   END
LPF ALTER_EFFECT INT_VAR match_parameter1 = 10 match_opcode = 267 parameter1 = EVAL "%RA_Held%" 	   END
LPF ALTER_EFFECT INT_VAR match_parameter1 = 11 match_opcode = 267 parameter1 = EVAL "%RA_Paralyzed%"   END

COPY "IHateUndead\Spl\RAUP1.spl"  override SAY NAME1 @107	SAY UNIDENTIFIED_DESC @108

COPY "IHateUndead\Spl\RAUP1.bam"  override

COPY "IHateUndead\Spl\RAUP.2da"   "override/RAUP1.2da"

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_BLESS[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_BLESS~	RET	spell_res	END

APPEND ~RAUP1.2da~ ~BLESS %spell_res% 3~

END

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_DETECT_EVIL[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_DETECT_EVIL~	RET	spell_res	END

APPEND ~RAUP1.2da~ ~DETECT_EVIL %spell_res% 3~

END

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_PROTECT_FROM_EVIL[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_PROTECT_FROM_EVIL~	RET	spell_res	END

APPEND ~RAUP1.2da~ ~PROTECTION_FROM_EVIL %spell_res% 3~

END

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_REMOVE_FEAR[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_REMOVE_FEAR~	RET	spell_res	END

APPEND ~RAUP1.2da~ ~REMOVE_FEAR %spell_res% 3~

END

COPY_EXISTING ~RAUP1.2da~ override
PRETTY_PRINT_2DA

COPY "IHateUndead\Spl\RAUP2.spl"  override SAY NAME1 @109	SAY UNIDENTIFIED_DESC @110

COPY "IHateUndead\Spl\RAUP2.bam"  override

COPY "IHateUndead\Spl\RAUP.2da"   "override/RAUP2.2da"

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_CURE_DISEASE[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_CURE_DISEASE~	RET	spell_res	END

APPEND ~RAUP2.2da~ ~CURE_DISEASE %spell_res% 3~

END

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_REMOVE_PARALYSIS[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_REMOVE_PARALYSIS~	RET	spell_res	END

APPEND ~RAUP2.2da~ ~REMOVE_PARALYSIS %spell_res% 3~

END

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_SLOW_POISON[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_SLOW_POISON~	RET	spell_res	END

APPEND ~RAUP2.2da~ ~SLOW_POISON %spell_res% 3~

END

COPY_EXISTING ~RAUP2.2da~ override
PRETTY_PRINT_2DA

COPY "IHateUndead\Spl\RAUP3.spl"  override SAY NAME1 @111	SAY UNIDENTIFIED_DESC @112

COPY "IHateUndead\Spl\RAUP3.bam"  override

COPY "IHateUndead\Spl\RAUP.2da"   "override/RAUP3.2da"

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_DEATH_WARD[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_DEATH_WARD~	RET	spell_res	END

APPEND ~RAUP3.2da~ ~DEATH_WARD %spell_res% 3~

END

ACTION_IF	FILE_CONTAINS_EVALUATED	(~SPELL.IDS~	~[ %TAB%]CLERIC_NEGATIVE_PLANE_PROTECTION[ %TAB%%WNL%%LNL%%MNL%$]~)	BEGIN
LAF 	RES_NUM_OF_SPELL_NAME STR_VAR	spell_name = ~CLERIC_NEGATIVE_PLANE_PROTECTION~	RET	spell_res	END

APPEND ~RAUP3.2da~ ~NEGATIVE_PLANE_PROTECTION %spell_res% 3~

END

COPY_EXISTING ~RAUP3.2da~ override
PRETTY_PRINT_2DA

//Restrictions

COPY_EXISTING_REGEXP ~.*\.itm~ override
	READ_BYTE 0x31 proficiency
	SET match = 0
	PATCH_MATCH proficiency WITH 
		89 91 93 94 95 96 99 100 104 105 106 107  BEGIN
		  LPF ADD_ITEM_EQEFFECT
			INT_VAR
			  opcode = 319
			  target = 1
			  parameter1 = (RAHUUP + 0x4000)
			  parameter2 = 9
			  timing = 2
		END
	SET match = 1
		END
		DEFAULT
		END
	PATCH_IF (SOURCE_SIZE > 0x71) AND (match = 0) BEGIN
		READ_BYTE 0x18 flags1
		PATCH_IF ((flags1 & BIT3) = BIT3) BEGIN
			READ_ASCII	0x22 animation (2)
			TO_UPPER animation
			PATCH_MATCH	"%animation%" WITH
				"4A" "3A" BEGIN
					LPF ~ADD_ITEM_EQEFFECT~ INT_VAR opcode = 319 target = 1 timing = 2 parameter1 = IDS_OF_SYMBOL (~Kit~ ~RAHUUP~) parameter2 = 9 END
				END
				DEFAULT
			END
		END
	END
BUT_ONLY

// EE : Workaround to display the correct fallen status in character screens. Kindly provided by Gwendolyne.

ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
	ACTION_CLEAR_ARRAY GW_Fallen_Kits
	ACTION_DEFINE_ASSOCIATIVE_ARRAY GW_Fallen_Kits BEGIN
	105,	106	=> RAHUUP
	END
	ACTION_PHP_EACH GW_Fallen_Kits AS GW_kits => GW_kit_name BEGIN
		COPY_EXISTING - ~clastext.2da~ ~override~
			COUNT_2DA_COLS cols									// amount of columns
			READ_2DA_ENTRIES_NOW kittable cols					// read all file into memory  
			FOR (row = 1 ; row < kittable ; ++row) BEGIN		// iterate over rows
				READ_2DA_ENTRY_FORMER kittable row 0 ~kit_name~	// read column value
				PATCH_IF ~%kit_name%~ STRING_EQUAL_CASE ~%GW_kit_name%~ BEGIN
					READ_2DA_ENTRY_FORMER kittable row 1 kit_classid
					READ_2DA_ENTRY_FORMER kittable row 2 kit_kitid
					READ_2DA_ENTRY_FORMER kittable row 4 kit_desc
					READ_2DA_ENTRY_FORMER kittable row 6 kit_bio
					READ_2DA_ENTRY_FORMER kittable row 8 kit_briefdesc
					SET patch_lower = RESOLVE_STR_REF ((AT %GW_kits_0%))
					SET patch_mixed = RESOLVE_STR_REF ((AT %GW_kits_1%))
					SET patch_fallen = 1
					SET patch_fallen_notice = "-1"
					SPRINT patch_clastext "FALLEN_%GW_kit_name% %kit_classid% %kit_kitid% %patch_lower% %kit_desc% %patch_mixed% %kit_bio% %patch_fallen% %kit_briefdesc% %patch_fallen_notice%"
					i = kittable
					INNER_ACTION BEGIN APPEND clastext.2da "%patch_clastext%" UNLESS "FALLEN_%GW_kit_name%" END
				END
			END
	END
	ACTION_CLEAR_ARRAY GW_Fallen_Kits
END

//EoF