//Thanks Subtledoctor for showing me how to fix the mess I did.

ACTION_IF (!FILE_EXISTS_IN_GAME ~RASPHERE.marker~) BEGIN

ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
  COPY_EXISTING ~clastext.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~
	  PATCH_IF ((~%text%~ STRING_EQUAL_CASE ~UNDEAD_HUNTER~) AND (!GAME_IS ~iwdee~)) BEGIN
	    SET_2DA_ENTRY %row% 4 cols RESOLVE_STR_REF (@401)
	  END 
	  PATCH_IF ((~%text%~ STRING_EQUAL_CASE ~UNDEAD_HUNTER~) AND (GAME_IS ~iwdee~)) BEGIN
		SET_2DA_ENTRY %row% 4 cols RESOLVE_STR_REF (@402)
	  END	
	END
  BUT_ONLY
END
ACTION_IF (FILE_EXISTS_IN_GAME ~sodcltxt.2da~) BEGIN
  COPY_EXISTING ~sodcltxt.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~
	  PATCH_IF ((~%text%~ STRING_EQUAL_CASE ~UNDEAD_HUNTER~) AND (!GAME_IS ~iwdee~)) BEGIN
	    SET_2DA_ENTRY %row% 4 cols RESOLVE_STR_REF (@401)
	  END 
	  PATCH_IF ((~%text%~ STRING_EQUAL_CASE ~UNDEAD_HUNTER~) AND (GAME_IS ~iwdee~)) BEGIN
		SET_2DA_ENTRY %row% 4 cols RESOLVE_STR_REF (@402)
	  END
	END
  BUT_ONLY
END
ACTION_IF (FILE_EXISTS_IN_GAME ~kitlist.2da~) BEGIN
  COPY_EXISTING ~kitlist.2da~ ~override~
    COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~text~
	  PATCH_IF ((~%text%~ STRING_EQUAL_CASE ~UNDEAD_HUNTER~) AND (!GAME_IS ~iwdee~)) BEGIN
	    SET_2DA_ENTRY %row% 4 cols RESOLVE_STR_REF (@401)
	  END 
	  PATCH_IF ((~%text%~ STRING_EQUAL_CASE ~UNDEAD_HUNTER~) AND (GAME_IS ~iwdee~)) BEGIN
		SET_2DA_ENTRY %row% 4 cols RESOLVE_STR_REF (@402)
	  END
	END
  BUT_ONLY
END

END ELSE BEGIN

ACTION_IF (FILE_EXISTS_IN_GAME ~clastext.2da~) BEGIN
  COPY_EXISTING ~clastext.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~
	  PATCH_IF ((~%text%~ STRING_EQUAL_CASE ~UNDEAD_HUNTER~) AND (!GAME_IS ~iwdee~)) BEGIN
	    SET_2DA_ENTRY %row% 4 cols RESOLVE_STR_REF (@405)
	  END 
	  PATCH_IF ((~%text%~ STRING_EQUAL_CASE ~UNDEAD_HUNTER~) AND (GAME_IS ~iwdee~)) BEGIN
		SET_2DA_ENTRY %row% 4 cols RESOLVE_STR_REF (@406)
	  END	
	END
  BUT_ONLY
END
ACTION_IF (FILE_EXISTS_IN_GAME ~sodcltxt.2da~) BEGIN
  COPY_EXISTING ~sodcltxt.2da~ ~override~
	COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 0 ~text~
	  PATCH_IF ((~%text%~ STRING_EQUAL_CASE ~UNDEAD_HUNTER~) AND (!GAME_IS ~iwdee~)) BEGIN
	    SET_2DA_ENTRY %row% 4 cols RESOLVE_STR_REF (@405)
	  END 
	  PATCH_IF ((~%text%~ STRING_EQUAL_CASE ~UNDEAD_HUNTER~) AND (GAME_IS ~iwdee~)) BEGIN
		SET_2DA_ENTRY %row% 4 cols RESOLVE_STR_REF (@406)
	  END
	END
  BUT_ONLY
END
ACTION_IF (FILE_EXISTS_IN_GAME ~kitlist.2da~) BEGIN
  COPY_EXISTING ~kitlist.2da~ ~override~
    COUNT_2DA_COLS cols
	READ_2DA_ENTRIES_NOW rows cols
	FOR (row = 1; row < rows; ++row) BEGIN
	  READ_2DA_ENTRY_FORMER rows row 1 ~text~
	  PATCH_IF ((~%text%~ STRING_EQUAL_CASE ~UNDEAD_HUNTER~) AND (!GAME_IS ~iwdee~)) BEGIN
	    SET_2DA_ENTRY %row% 4 cols RESOLVE_STR_REF (@405)
	  END 
	  PATCH_IF ((~%text%~ STRING_EQUAL_CASE ~UNDEAD_HUNTER~) AND (GAME_IS ~iwdee~)) BEGIN
		SET_2DA_ENTRY %row% 4 cols RESOLVE_STR_REF (@406)
	  END
	END
  BUT_ONLY
END

END

COPY_EXISTING ~CLABPA04.2DA~ ~override~
SET_2DA_ENTRY 6 1 40 ~AP_RAUHF~
SET_2DA_ENTRY 6 3 40 ~AP_RAUHF~
SET_2DA_ENTRY 4 5 40 ~GA_RAUH1~
PRETTY_PRINT_2DA
BUT_ONLY

CREATE spl ~RAUHF~

COPY_EXISTING ~RAUHF.spl~ override
LPF ADD_ABILITIES	   INT_VAR abil = 2 END
LPF ALTER_SPELL_HEADER INT_VAR header = 2 min_level = 3  END
LPF ADD_SPELL_EFFECT   INT_VAR header = 1 opcode = 321 target = 2 timing = 9                                               STR_VAR insert_point = 0 resource = ~RAUHF~ END
LPF ADD_SPELL_EFFECT   INT_VAR header = 1 opcode = 178 target = 2 timing = 9 parameter1 = 4    parameter2 = 3  special = 3 STR_VAR insert_point = 1  END
LPF ADD_SPELL_EFFECT   INT_VAR header = 1 opcode = 179 target = 2 timing = 9 parameter1 = 4    parameter2 = 3  special = 3 STR_VAR insert_point = 2  END
LPF ADD_SPELL_EFFECT   INT_VAR header = 2 opcode = 321 target = 2 timing = 9                                               STR_VAR insert_point = 0 resource = ~RAUHF~ END
LPF ADD_SPELL_EFFECT   INT_VAR header = 2 opcode = 178 target = 2 timing = 9 parameter1 = 4    parameter2 = 3  special = 3 STR_VAR insert_point = 1  END
LPF ADD_SPELL_EFFECT   INT_VAR header = 2 opcode = 179 target = 2 timing = 9 parameter1 = 4    parameter2 = 3  special = 3 STR_VAR insert_point = 2  END
LPF ADD_SPELL_EFFECT   INT_VAR header = 2 opcode = 323 target = 2 timing = 9 parameter1 = 2                                STR_VAR insert_point = 3  END
LPF ADD_SPELL_EFFECT   INT_VAR header = 2 opcode = 206 target = 2 timing = 9 parameter1 = ~-1~                             STR_VAR insert_point = 4 resource = ~RAUHF~ END

COPY ~IHateUndead\Spl\RAUH1.spl~ override SAY NAME1 @403	SAY UNIDENTIFIED_DESC @404

COPY ~IHateUndead\Spl\RAUH1.itm~ override SAY NAME1 @403	SAY NAME2 @403

COPY ~IHateUndead\Spl\RAUH1.bam~ override
    
//EoF